[package]
name = "baglama2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

mimalloc = { version = "0.1", features = ["secure"] }
mysql_async = "0.36"
tokio = { version = "^1", features = ["full", "rt-multi-thread"] }
serde_json = "^1"
chrono = "0.4"
anyhow = "1"
bzip2 = "0.5"
wikimisc = { git = "https://github.com/magnusmanske/wikimisc" , features = ["wikidata","database","site-matrix"] }
log = "0.4"
env_logger = "0.11"
flate2 = "1"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }

[profile.release]
opt-level = 3
lto = 'fat'
codegen-units = 1
